### ISSUE TITLE
Out of memory & killed when attempting to write

### ISSUE THREAD

**Issue by deliciouslytyped** [jedevc/mafs#1] opened 2019-06-01 02:34 UTC
I haven't figured out how to debug this, but any variant of `fs.write()` that I tried, causes python to gorge itself on RAM and then get killed. At least on my machine. I tried the `numbers` example and it also fails for me.

I did an strace, which didn't really yield any information except python spamming `mmap` calls.
I did some printf debugging and it __looks__ to me like the callback isn't even being run.

**Comment by deliciouslytyped** [comment] 2019-06-01 03:16
After additional experimentation, the issue seems to be limited to the single argument variant of the write callback.

**Comment by jedevc** [comment] 2019-06-02 10:10
Yeah, I've run into this before as well - the way that write works is quite tricky. I'll have a look and see if I can work out where this is coming from. I'd take a guess that the issue is coming from the fact that writing has to be buffered for the single argument variant so it can be passed in properly.

**Comment by jedevc** [comment] 2019-06-02 10:30
Fantastic, I've found the issue, and patched it in 5d4ad3a.
It came from a previous misunderstanding of `itertools.count`, which was then be converted into a list. This caused the python interpreter to essentially try to allocate an infinite amount of memory to contain the infinite sequence.

It should be fixed now, I'll be putting the new version on PyPi soon.

**Closed as completed by jedevc** 2019-06-02 10:30 UTC
